[package]
name = "flv-util"
version = "0.1.0"
authors = ["fluvio.io"]
edition = "2018"

[features]
default = []
fixture = []

[dependencies]
env_logger = "0.6.2"
chrono = { version = "0.4.7"}
log = "0.4.8"